### ISSUE TITLE
标签页面会出现重复tag

### ISSUE THREAD

**Issue by jimicat** [ChurchTao/PlainPage#1]
![image](https://github.com/user-attachments/assets/c4ec7800-370d-43b9-8986-a7f21cae6cf5)

**Comment by ChurchTao** [comment]
收到，马上改

**Comment by ChurchTao** [comment]
已修改

https://github.com/ChurchTao/PlainPage/commit/f4f26ee53245cf11a5b631abd6f7431ae01617f9
